-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 11:29:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Treningsøkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Treningsøkt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Treningsøkt` (
  `idTreningsøkt` INT NOT NULL,
  `Dato` DATE NOT NULL,
  `Tidspunkt` TIME NOT NULL,
  `Varighet` INT NOT NULL,
  `Form` INT(10) NOT NULL,
  `Innsats` INT(10) NOT NULL,
  PRIMARY KEY (`idTreningsøkt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notat` (
  `idNotat` INT NOT NULL,
  `Tekst` VARCHAR(450) NULL,
  `idTreningsøkt` INT NOT NULL,
  PRIMARY KEY (`idNotat`, `idTreningsøkt`),
  CONSTRAINT `fk_Notat_Treningsøkt`
    FOREIGN KEY (`idTreningsøkt`)
    REFERENCES `mydb`.`Treningsøkt` (`idTreningsøkt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Notat_Treningsøkt_idx` ON `mydb`.`Notat` (`idTreningsøkt` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Øvelsegruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Øvelsegruppe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Øvelsegruppe` (
  `idØvelsegruppe` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idØvelsegruppe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friøvelse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friøvelse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friøvelse` (
  `idFriøvelse` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Set` INT NOT NULL,
  `Reps` INT NOT NULL,
  `Kilo` INT NOT NULL,
  `Beskrivelse` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idFriøvelse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friøvelse_has_Øvelsegruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friøvelse_has_Øvelsegruppe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friøvelse_has_Øvelsegruppe` (
  `idFriøvelse` INT NOT NULL,
  `idØvelsegruppe` INT NOT NULL,
  PRIMARY KEY (`idFriøvelse`, `idØvelsegruppe`),
  CONSTRAINT `fk_Friøvelse_has_Øvelsegruppe_Friøvelse1`
    FOREIGN KEY (`idFriøvelse`)
    REFERENCES `mydb`.`Friøvelse` (`idFriøvelse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friøvelse_has_Øvelsegruppe_Øvelsegruppe1`
    FOREIGN KEY (`idØvelsegruppe`)
    REFERENCES `mydb`.`Øvelsegruppe` (`idØvelsegruppe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Friøvelse_has_Øvelsegruppe_Øvelsegruppe1_idx` ON `mydb`.`Friøvelse_has_Øvelsegruppe` (`idØvelsegruppe` ASC);

CREATE INDEX `fk_Friøvelse_has_Øvelsegruppe_Friøvelse1_idx` ON `mydb`.`Friøvelse_has_Øvelsegruppe` (`idFriøvelse` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Apparat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apparat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apparat` (
  `apparatID` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Beskrivelse` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`apparatID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apparatøvelse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apparatøvelse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apparatøvelse` (
  `idApparatØvelse` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Set` INT NOT NULL,
  `Reps` INT NOT NULL,
  `Kilo` INT NOT NULL,
  `apparatID` INT NOT NULL,
  PRIMARY KEY (`idApparatØvelse`),
  CONSTRAINT `fk_ApparatØvelse_Apparat1`
    FOREIGN KEY (`apparatID`)
    REFERENCES `mydb`.`Apparat` (`apparatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ApparatØvelse_Apparat1_idx` ON `mydb`.`Apparatøvelse` (`apparatID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Treningsøkt_has_Friøvelse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Treningsøkt_has_Friøvelse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Treningsøkt_has_Friøvelse` (
  `idTreningsøkt` INT NOT NULL,
  `idFriøvelse` INT NOT NULL,
  PRIMARY KEY (`idTreningsøkt`, `idFriøvelse`),
  CONSTRAINT `fk_Treningsøkt_has_Friøvelse_Treningsøkt1`
    FOREIGN KEY (`idTreningsøkt`)
    REFERENCES `mydb`.`Treningsøkt` (`idTreningsøkt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treningsøkt_has_Friøvelse_Friøvelse1`
    FOREIGN KEY (`idFriøvelse`)
    REFERENCES `mydb`.`Friøvelse` (`idFriøvelse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Treningsøkt_has_Friøvelse_Friøvelse1_idx` ON `mydb`.`Treningsøkt_has_Friøvelse` (`idFriøvelse` ASC);

CREATE INDEX `fk_Treningsøkt_has_Friøvelse_Treningsøkt1_idx` ON `mydb`.`Treningsøkt_has_Friøvelse` (`idTreningsøkt` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Treningsøkt_has_ApparatØvelse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Treningsøkt_has_ApparatØvelse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Treningsøkt_has_ApparatØvelse` (
  `idTreningsøkt` INT NOT NULL,
  `idApparatØvelse` INT NOT NULL,
  PRIMARY KEY (`idTreningsøkt`, `idApparatØvelse`),
  CONSTRAINT `fk_Treningsøkt_has_ApparatØvelse_Treningsøkt1`
    FOREIGN KEY (`idTreningsøkt`)
    REFERENCES `mydb`.`Treningsøkt` (`idTreningsøkt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treningsøkt_has_ApparatØvelse_ApparatØvelse1`
    FOREIGN KEY (`idApparatØvelse`)
    REFERENCES `mydb`.`Apparatøvelse` (`idApparatØvelse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Treningsøkt_has_ApparatØvelse_ApparatØvelse1_idx` ON `mydb`.`Treningsøkt_has_ApparatØvelse` (`idApparatØvelse` ASC);

CREATE INDEX `fk_Treningsøkt_has_ApparatØvelse_Treningsøkt1_idx` ON `mydb`.`Treningsøkt_has_ApparatØvelse` (`idTreningsøkt` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ApparatØvelse_has_Øvelsegruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApparatØvelse_has_Øvelsegruppe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ApparatØvelse_has_Øvelsegruppe` (
  `idApparatØvelse` INT NOT NULL,
  `idØvelsegruppe` INT NOT NULL,
  PRIMARY KEY (`idApparatØvelse`, `idØvelsegruppe`),
  CONSTRAINT `fk_ApparatØvelse_has_Øvelsegruppe_ApparatØvelse1`
    FOREIGN KEY (`idApparatØvelse`)
    REFERENCES `mydb`.`Apparatøvelse` (`idApparatØvelse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ApparatØvelse_has_Øvelsegruppe_Øvelsegruppe1`
    FOREIGN KEY (`idØvelsegruppe`)
    REFERENCES `mydb`.`Øvelsegruppe` (`idØvelsegruppe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ApparatØvelse_has_Øvelsegruppe_Øvelsegruppe1_idx` ON `mydb`.`ApparatØvelse_has_Øvelsegruppe` (`idØvelsegruppe` ASC);

CREATE INDEX `fk_ApparatØvelse_has_Øvelsegruppe_ApparatØvelse1_idx` ON `mydb`.`ApparatØvelse_has_Øvelsegruppe` (`idApparatØvelse` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
